# YouTube Video: https://www.youtube.com/watch?v=rhBZqEWsZU4
# Variables that contains the user credentials to access Twitter API 
ACCESS_TOKEN = "804258028526522368-0bHL5szbFKM5XXXXXXXXXXXXXX"
ACCESS_TOKEN_SECRET = "QHH8B9TlFx7cQalTdr5dYt3XXXXXXXXXXXx"
CONSUMER_KEY = "tD7EQnr0oHClPVZu85RVnTutGXXXXXXXXXXXXXXXX"
CONSUMER_SECRET = "SlwfMY3GcQiuY9M2eVitbHqXXXXXXXXXXXXXXX"

